/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registroes.Vista;

import com.mycompany.registroes.Controlador.CtrlEstAgg;

/**
 *
 * @author chimil
 */
public class FrmResEst extends javax.swing.JFrame {

    private CtrlEstAgg ctrlEst;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmResEst.class.getName());
    
    public FrmResEst() {
        initComponents();
        
        ctrlEst = new CtrlEstAgg(this);
    }
    public void vaciasCajas(){
        this.txtNControl.setText("");
        this.txtNombre.setText("");
        this.txtCarrera.setText("");
        this.Txtpromedio.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblGuardar = new javax.swing.JLabel();
        lblListar = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNControl = new javax.swing.JTextField();
        Txtpromedio = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NumControl");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel3.setText("Carrera");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel4.setText("Promedio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registro estudiantes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, -1));

        lblGuardar.setText("Guardar");
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(lblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 309, -1, 20));

        lblListar.setText("LIstar");
        lblListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListarMouseClicked(evt);
            }
        });
        getContentPane().add(lblListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, 30));

        txtNControl.addActionListener(this::txtNControlActionPerformed);
        getContentPane().add(txtNControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 120, 30));
        getContentPane().add(Txtpromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 120, 30));
        getContentPane().add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
        ctrlEst.IngresarDatos(this.txtNControl.getText(),this.txtNombre.getText(),this.txtCarrera.getText(),((byte)Integer.parseInt(this.Txtpromedio.getText())));
        vaciar();
    }//GEN-LAST:event_lblGuardarMouseClicked

    private void txtNControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNControlActionPerformed

    private void lblListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListarMouseClicked
        // TODO add your handling code here:
        FrmListEst frmEst = new FrmListEst();
        frmEst.setVisible(true);
    }//GEN-LAST:event_lblListarMouseClicked

    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(() -> new FrmResEst().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txtpromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblListar;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtNControl;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void vaciar() {
        this.Txtpromedio.setText("");
        this.txtCarrera.setText("");
        this.txtNControl.setText("");
        this.txtNombre.setText("");
        this.Txtpromedio.setText("");
    }
}
